### ISSUE TITLE
How to go "back to old client"

### ISSUE THREAD

**Issue by tristanlins** [contao-community-alliance/composer-client#232]
The "back to old client" function is a little bit tricky. It works correctly only if composer itself works, because we run a complete uninstall. But in the case you wan't to go back is, when composer probably not work!

After some discussion we will remove the automatic function complete and write a documentation how to remove the composer client.

We already have the problem, that 99% of the users who want to go back have problems with composer and need to remove it by hand or reinstall their installation. So this seems to be the only acceptable solution for this.

**Comment by fritzmg** [comment]
Currently the situation has changed a bit. Users might want to go back with a "working" composer as well, because they cannot run a composer update anymore due to the increased memory footprint or because of the past negative experience due to the automatic `composer.phar` update.

**Comment by fritzmg** [comment]
I have updated the Wiki with instructions on how to switch back: https://github.com/contao-community-alliance/composer-client/wiki/Switch-back

**Comment by discordier** [comment]
Thanks
