### ISSUE TITLE
Rename project to "extension repository 3"

### ISSUE THREAD

**Issue by tristanlins** [contao-community-alliance/composer-client#235]
@toflar has proposed to change the whole project name to "extension repository 3 project", or short ER3.

`contao-community-alliance/composer-client` would be `contao-community-alliance/er3-client` then.
`contao-community-alliance/composer-plugin` would be `contao-community-alliance/er3-plugin` then.
`contao-community-alliance/composer-repository` would be `contao-community-alliance/er3-repository` then.

I'm not averse to the idea. A name change would make the difference between the Composer project and our project clearer.

**Comment by discordier** [comment]
Tenside is alive at http://github.com/tenside.
