### ISSUE TITLE
Php Fehler wenn gitHub Repo gelöscht wurde

### ISSUE THREAD

**Issue by garyee** [contao-community-alliance/composer-client#242]
Okay ich weiß, es ist ein Spezialfall, aber wenn ich ein GitHub Repo in der composer.json habe und das dann lösche, kann ich meine Pakete nicht mehr aktualisieren ohne das ein Fehler kommt.
Und deinstallieren kann ich es auch nicht.

Der Fehler geht so ähnlich wie:
```
Fatal error: Uncaught exception Composer\Repository\InvalidRepositoryException with message No valid composer.json was found in any branch or tag of https://github.com/..... , could not load a package from it. thrown in phar://composer/composer.phar/src/Composer/Repository/VcsRepository.php on line 264
```

Es wäre gut wenn ich die anderen Pakete wenigstens aktualisieren könnte ohne das der PHP Fehler kommt, den könnte man vielleicht in eine Error Message packen.
Und wenn ich das deinstallieren möchte, wäre es gut wenn das auch wirklich gemacht wird, also fände ich.

**Comment by garyee** [comment]
Wenn ich die Erweiterung drinn lasse und das ER durchsuchen will, kommt folgender Fehler.
```
Fatal error: Uncaught exception RuntimeException with message Failed to execute git clone --mirror 'https://...:***@github.com/....' '/www/htdocs/.... /' error: The requested URL returned error: 403 while accessing https://....:x-oauth-basic@github.com/..... fatal: HTTP request failed thrown in phar://composer/composer.phar/src/Composer/Util/Git.php on line 193
```

**Comment by discordier** [comment]
Wont fix this, composer simply stops when you mess up your repository config and we do not intend to filter this.
If you break the config, expect the system to not work. ;)
