### ISSUE TITLE
Strange caret behaviour in Composer.json file editor in BE

### ISSUE THREAD

**Issue by garyee** [contao-community-alliance/composer-client#243]
Hi,

so it is the second time on a contao installation I got this fault which is kind of strange.
The caret is shifted. So when it is on the end of a line it is 3(or more) places behind the last character and when I try to edit it edits the last character. So the carets is rendered one behind its real position.
Maybe it is because of the tabs on the beginning of the line.
![unbenannt](https://cloud.githubusercontent.com/assets/5537949/5998508/9a03d326-aac8-11e4-9840-29e633e82fe4.PNG)
So in this picture the caret is 7 behind the comma and if I would press backspace it would delete the comma.

**Comment by discordier** [comment]
Strange, I thought we have fixed this with 89adc6f2bd1fe5614617ae8de16a0cf028a29a32 a long time ago.

**Comment by garyee** [comment]
AH ... vielleicht sollte ich mir angewöhnen Versionsnummer dazu zu schreiben:
![unbenannt](https://cloud.githubusercontent.com/assets/5537949/6026010/3bdc716c-abd7-11e4-8f90-aedb684a69bf.PNG)
Die Seite hing zwar eine ganze Zeit in der Schwebe, aber so alt ist die jetzt auch nicht.

**Comment by discordier** [comment]
As stated in the commit, it is fixed in composer-client 0.14, 0.15, 0.15.1.
Therefore the very next version to the one you are using. :)
Please upgrade from (deprecated) `contao-community-alliance/composer` to `contao-community-alliance/composer-client` and you should be all set.
