### ISSUE TITLE
Why are classes used different in frontend and backend?

### ISSUE THREAD

**Issue by Defcon0** [contao-community-alliance/composer-client#246]
Hello,

it seems that the composer client uses different php class files of installed extensions in frontend (composer/vendor/...) and backend (system/modules/...). So when developing extensions, I have change it in multiple files :-( Why is that? Couldn't it only use the files in system/modules/...?

Bye Defcon0

**Comment by BugBuster1701** [comment]
This is probably the autoloader. Classes (FE/BE) are loaded preferred from  composer/vendor, configurations from system/modules. 
Autoloader: first the composer autoloader then the contao autloader
Configs, language files etc.: only Contao system.

**Comment by tristanlins** [comment]
For development you should use "prefered install: source" in the composer settings. Then the client will create symlinks into system/modules instead of copies.
