### ISSUE TITLE
Ersteinrichtung Composer, Design verschoben

### ISSUE THREAD

**Issue by BugBuster1701** [contao-community-alliance/composer-client#247]
Grad bei Installation Contao 3.5.0 mit Composer-Client 0.15.1
![composer-einrichtung](https://cloud.githubusercontent.com/assets/1218809/6906368/c880e5b2-d72e-11e4-95a5-aaf16bd28b2c.png)

**Comment by frontendschlampe** [comment]
Kann ich bestätigen. Wollte ich heute Mittag schon @discordier sagen, dachte aber dann, dass es an mir liegt! :-)

**Comment by frontendschlampe** [comment]
es kommen folgende Fehlermeldungen:

```
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (migrate.js, line 0) http://meine-domain.tld/system/modules/!composer/assets/js/migrate.js

[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (backend.css, line 0) http://meine-domain.tld/system/modules/!composer/assets/css/backend.css

[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (icon.png, line 0) http://meine-domain.tld/system/modules/!composer/assets/images/icon.png
```

**Comment by frontendschlampe** [comment]
Hey @BugBuster1701,

es hat die ```.htaccess``` gefehlt - habe ich soeben im ER hinzugefügt. Könntest du das eventuell nochmal testen? Danke. :-)

**Comment by BugBuster1701** [comment]
aja, jetzt besser und bunt :-)
