### ISSUE TITLE
No ACE in BE when foreign resources are blocked

### ISSUE THREAD

**Issue by Aybee** [contao-community-alliance/composer-client#248]
Wäre es nicht besser, den ACE so einzubinden, wie es allgemein in Contao gemacht wird?

contao-community-alliance/composer-client
https://github.com/contao-community-alliance/composer-client/blob/96651f95f6bf2003f00fb46dfa5bce1727745d3b/src/system/modules/!composer/templates/be_composer_client_editor.html5#L27

contao/core
https://github.com/contao/core/blob/960155bf2c6225cdf2f3d2f21fb9ae9492f86a11/system/config/ace.php#L19

Ich hatte mich auf jeden Fall gewundert, warum der Expertenmodus so seltsam aussieht, bis ich gesehen habe, dass der ACE hier von einer Fremddomain eingebunden wird. Ich sperre grundsätzlich Resourcen, die von Fremddomains geladen werden. Ich musste extra ein neues Template anlegen, damit der interne ACE benutzt wird.

**Comment by discordier** [comment]
Das geht erst, wenn wir die dependency des core auf >3.2 setzen. Daher ist es auch eine "Fremddomain", denn in 2.11 war der ace noch nicht so enthalten.

**Comment by discordier** [comment]
Please test with ce646bc in the hotfix branch so we can release asap.

**Comment by Aybee** [comment]
Ich habe jetzt leider keine Installation am Start, mit der ich das testen könnte, sorry.
