### ISSUE TITLE
Cannot install any extension after update packages

### ISSUE THREAD

**Issue by bizon1** [contao-community-alliance/composer-client#249]
Contao 3.4.5
After trying to install 'contao-legacy/con4gis_maps ' I got the following warning:

    Warning: Contao core was about to get installed but has been found in project root, to recover from this problem please restart the operation

and in the black box:

    Loading composer repositories with package information
    Updating dependencies

To restart this operation didn't resolve the problem and now I cannot install any extension at all.

**Comment by discordier** [comment]
It appears that the plugin has not been properly installed.
Could you provide us with a list of the contents of `TL_ROOT/composer/vendor` (including the first sublevel)?
