### ISSUE TITLE
[0.15.2] Textausgabe nicht mehr farbig (Backend)

### ISSUE THREAD

**Issue by BugBuster1701** [contao-community-alliance/composer-client#253]
```
[32mLoading composer repositories with package information[39m
[32mUpdating dependencies[39m
Nothing to install or update
[32mGenerating autoload files[39m
```
contao-community-alliance/composer-client	0.15.2
contao-community-alliance/composer-plugin	2.3.5

**Comment by discordier** [comment]
Standalone modus?
Bitte mehr Details zu deinem runtime environment.

**Comment by BugBuster1701** [comment]
Als ich grad Paketverwaltung -> Einstellungen -> Composer aktualisieren ausführte, waren die Meldungen wieder farbig.
Ausführungsmodus ist: während der aktuellen http-Anfrage
Installiert ist jetzt: Composer version 1.0-dev vom  2015-07-07 14:15:59
Leider keine Ahnung was vorher drauf war.

**Comment by discordier** [comment]
Wenn es weider auftritt bitte reopen.

**Comment by BugBuster1701** [comment]
Zu Hause hatte ich das auch, da ist noch ne ältere composer.phar installiert vom 10.5.2015
Composer version 1.0-dev (4eb8ecff9cd136c4c2829164db1a55ad9d2de616) 2015-05-10 19:56:28

Vielleicht hab es ja ein Fix in der aktuellen Version
Composer version 1.0-dev (dbdd4978a7dd4cd29d0d7dfc912aab404245b736) 2015-07-07 14:15:59
