### ISSUE TITLE
Übersetzung "Enable Profiling" nicht möglich auf Transifex

### ISSUE THREAD

**Issue by BugBuster1701** [contao-community-alliance/composer-client#254]
Die Variable ```$GLOBALS['TL_LANG']['tl_settings']['composerProfiling']``` existiert nicht in der englischen Sprachdatei für tl_settings auf Transifex, daher kann es nicht übersetzt werden.
Auf Gitub ist es in en/tl_settings.php enthalten. Müsste wohl mal auf Transifex aktualisiert werden.

**Comment by discordier** [comment]
Should be fixed by now.
