### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by JLBA** [contao-community-alliance/composer-client#255]
Hi,

I'm using Contao 3.4.5 with Composer 0.15.2 (installed from contao/install.php). 

I could install metamodels/core dev_tng and metamodels/bundle_all. But now, when trying to search for an extension or to update installed packages, I get almost each time an "Internal server error" after many seconds waiting. If I go back, search and sometime update buttons are no more active. I reload the page and - sometime - I got the "black console frame" indicating all that was done. This way, yesterday, I could update metamodels/core and just now it said there was nothing to update. All this seems aleatory…

**Comment by discordier** [comment]
- What mode are you running in?
- What is the request timeout according to `phpinfo()`?
- What do the logs state?

**Comment by JLBA** [comment]
Hi Christian,

Today it seems to work after I’ve used system maintenance and recreated index.

I’ve just updated MM (4 files to update). 

Just afterthat, I could install syncCto ß2 too but : 
- the search worked fine ; I choose the ß2 version ; 
- I clicked on update packages and after 30 seconds I got the "internal server error" message ;
- I went back and then then saw the shell frame displaying that the files were downloaded ;
- I clicked again on update and had again the “internal server error” message ; 
- I went back again and click on udpate database which worked fine.

Here are your answer to undersatnd why I still get the “internal server error” message.

> What mode are you running in?
Dev release
> What is the request timeout according to phpinfo()?

> What do the logs state?
[Wed Jul 22 11:35:13 2015] [error] [client ::1] FastCGI: comm with server "/Applications/MAMP/fcgi-bin/php5.4.39.fcgi" aborted: idle timeout (30 sec), referer: http://lnh3-testconfigs:8888/c345/contao/main.php

Thanks

**Comment by discordier** [comment]
So there we have the problem. You have reached your cgi limit. Your webserver is configured to wait 30 seconds for the cgi script to perform any output while composer needs more than 30 seconds on your server.
Therefore the execution gets killed and your system is broken.
However, you might test if switiching to detached mode (in the backend, System /Settings / Composer settings) will solve your problem, it should. Please be aware, that this execution mode is not possible yet even allowed on all servers, so you might want to check back with your hosting provider first.

**Comment by JLBA** [comment]
This worked. Thanks.
