### ISSUE TITLE
If a search for "metamodels" don't return all results [0.15.2]

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [contao-community-alliance/composer-client#256]
If a search for "metamodels" don't return all results. If I search for "attribute_checkbox", the "metamodels/attribute_checkbox" is showed as result. "attribute_checkbox" is only one example.
The keyword metamodels is given in the composer.json and the attribute is kompatible.

**Comment by fritzmg** [comment]
Duplicate of #244
