### ISSUE TITLE
Resyncing packages in back end removes composer client in /composer/vendor

### ISSUE THREAD

**Issue by bezin** [contao-community-alliance/composer-client#257]
Hey there, 

I have an issue with the composer client in a Contao 3.5 installation. If I click on "resync packages" in the tools section of the composer client, I get several warnings like this one below:

```
Warning: symlink(): No such file or directory in C:\development\...\composer\vendor\contao-community-alliance\composer-plugin\src\ContaoCommunityAlliance\Composer\Plugin\SymlinkInstaller.php on line 215 
```

After that, all files in the repositories of the packages in /composer/vendor are deleted, including the composer-client, meaning it is not accesible from the back end. Only thing that works to fix that is resetting all those repositories manually. I am not sure which additional information I have to provide, but I'll gather everything needed. I am on Windows 8.1, using Wamp with PHP 5.5.12.

**Comment by discordier** [comment]
Is this still valid in 0.16.3?

**Comment by bezin** [comment]
Was not able to reproduce it yet. I am gonna watch it and keep you updated.

**Comment by discordier** [comment]
Thanks.
Mind if I close the issue?
Feel free to open a new one when it occurs again.
