### ISSUE TITLE
nested dependency wird im Backend nicht angezeigt

### ISSUE THREAD

**Issue by garyee** [contao-community-alliance/composer-client#258]
Hallo,

Ich habe eine eigene Erweiterung die noch nicht ER reif ist, diese benutzt eine Javascript Lib von gitHub.
Diese Js Lib ist allerdings nicht so gut maintained sodass ich sie geforkt habe um selbst Änderungen vorzunehmen.
Ich habe jetzt die Js Datein aus meiner Erweiterung rausgehauen und wollte statt dessen den Js Lib Fork von gitHub in die Dependencys reinnehmen.
Da habe ich festgestellt das in einer Composer.json einer Projekts die repositories mit dem Typen [VCS](https://getcomposer.org/doc/05-repositories.md#vcs) nicht aufgelöst gefunden werden.
Dann habe ich es jetzt gemacht wie [hier](https://donatstudios.com/Load-Gist-With-Composer). Da geht es auch, also die Datein des Forks landen im composer Ordner.
Nur wird das Projekt nicht in der Übersicht im Contao BE angezeigt.

Ich weiß nicht ob das ein Bug oder ein FR ist, da kenne ich mich mit composer zu wenig aus.
Es wäre gut wenn die Übersicht im BE vollständig wäre, find ich und vielleicht weiß jemand ob das mit den nicht auflösen in den Projekt dependencys normal ist.

Quelltext gibts [hier](https://github.com/garyee/contao-venobox/blob/master/composer.json)

Ps: Contao 3.4.5, Composer-client: 0.15.2

**Comment by tim-bec** [comment]
Hallo Gerald,

auch wenn das eher ins Forum gehört: Was genau meinst Du mit "wird das Projekt nicht in der Übersicht im Contao BE angezeigt."

**Comment by garyee** [comment]
Hallo,
danke für deine schnelle Antwort, habe den Button unten übersehen ... alles klar
