### ISSUE TITLE
[0.15.4] SSL Problem on windows

### ISSUE THREAD

**Issue by Zeromax** [contao-community-alliance/composer-client#261]
> The "https://legacy-packages-via.contao-community-alliance.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed Failed to enable crypto failed to open stream: operation failed

Is it possible to disable SSL verification on windows or via Config?
See line:
https://github.com/contao-community-alliance/composer-client/blob/2967fe5a13763ffc7029c83719aa180a61ddce81/src/system/modules/!composer/src/Downloader.php#L102
Add
```php
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
```

Then on windows everything works fine.

**Comment by fritzmg** [comment]
Just define a certificate: http://stackoverflow.com/questions/6400300/https-and-ssl3-get-server-certificatecertificate-verify-failed-ca-is-ok/16495053#16495053

**Comment by discordier** [comment]
These checks should circumvent the problem, shouldn't they?
https://github.com/contao-community-alliance/composer-client/blob/2967fe5a13763ffc7029c83719aa180a61ddce81/src/system/modules/!composer/src/Downloader.php#L155

**Comment by discordier** [comment]
what version of openssl is reported on your windows PHP?

**Comment by discordier** [comment]
@Zeromax is this still valid in 0.16.3?

**Comment by Zeromax** [comment]
@discordier Yes.
```

Fatal error: Uncaught exception Exception with message SSL certificate problem: unable to get local issuer certificate thrown in D:\www\contao-3.5.6\system\modules\!composer\src\Downloader.php on line 137

#0 D:\www\contao-3.5.6\system\modules\!composer\src\Downloader.php(40): ContaoCommunityAlliance\Contao\Composer\Downloader::curlDownload('https://getcomp...', 'D:\\www\\contao-3...')
#1 D:\www\contao-3.5.6\system\modules\!composer\src\Runtime.php(238): ContaoCommunityAlliance\Contao\Composer\Downloader::download('https://getcomp...', 'D:\\www\\contao-3...')
#2 D:\www\contao-3.5.6\system\modules\!composer\src\ClientBackend.php(278): ContaoCommunityAlliance\Contao\Composer\Runtime::updateComposer()
#3 D:\www\contao-3.5.6\system\modules\!composer\src\ClientBackend.php(125): ContaoCommunityAlliance\Contao\Composer\ClientBackend->loadComposer()
#4 D:\www\contao-3.5.6\system\modules\core\classes\Backend.php(423): ContaoCommunityAlliance\Contao\Composer\ClientBackend->generate()
#5 D:\www\contao-3.5.6\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('composer')
#6 D:\www\contao-3.5.6\contao\main.php(20): Contao\BackendMain->run()
#7 {main}
```

Just clicked on "composer update" Button. Now the package manager isn't reachable anymore.

**Comment by fritzmg** [comment]
You need to do what I said ;)

**Comment by Zeromax** [comment]
I do not want to do this. Its a problem of the contao composer plugin and it should fix and resolve it.

**Comment by fritzmg** [comment]
It is not. The problem occurs because your webserver is not configured correctly to allow secure connections over SSL.

**Comment by Zeromax** [comment]
It is. composer works fine from the command line. It is a Problem of the composer plugin and not composer.
And I can set up https://getcomposer.org/doc/06-config.md#secure-http if I want to.

**Comment by fritzmg** [comment]
> composer works fine from the command line.

This has nothing to do with composre, you are misunderstanding the problem. Look at the error message again:
```
Fatal error: Uncaught exception Exception with message SSL certificate problem: unable to get local issuer certificate thrown in D:\www\contao-3.5.6\system\modules\!composer\src\Downloader.php on line 137
```
The `composer-client` is trying to download something via cURL via a secured connection. In order for cURL to be able to do this, it needs a local issuer certificate. This is a basic requirement, which you must configure in your webserver appropriately. 

> And I can set up https://getcomposer.org/doc/06-config.md#secure-http if I want to.

Again, it has nothing to do with composer. The problem is simply, that cURL is unable to create a secure connection via SSL on your webserver. This has nothing to do with composer, the `composer-client` or the `composer-plugin`. You would and will run into the same problem with any other web application on your webserver that tries to create a connection via SSL with cURL.

**Comment by Zeromax** [comment]
Sorry about that. I am done with it...

**Comment by discordier** [comment]
Well, we could catch the exception and display a better error message but that is all we can do.

**Comment by backbone87** [comment]
definitiv ein nerviges problem, egtl sollte openssl automatisch nach den OS root certs suchen, aber das funktioniert anscheinend nicht so einfach.

xampp bringt ein ca-cert-bundle mit: `<path-to-xampp>\apache\bin\curl-ca-bundle.crt`

entweder man setzt es nur für curl:
`curl.cainfo=<path-to-xampp>\apache\bin\curl-ca-bundle.crt`

order auch für openssl allgemein: (wobei dies die autodetection deaktiviert)
`openssl.cafile=<path-to-xampp>\apache\bin\curl-ca-bundle.crt`

sofern man nicht regelmäßig manuell das cert bundle updated, um veraltet (und evtl. kompromitierte) certs zu verhindern, sollte man dies **AUF KEINEN FALL IN PRODUCTION ENVS EINSETZEN**

**Comment by backbone87** [comment]
jetzt noch was zur prüfung:
kann man nicht versuchen `https://www.google.com/` aufzurufen und wenn das zu SSL fehlern führt, den verify peer deaktivieren?

**Comment by backbone87** [comment]
noch besser wär vll wenn der client ein dummy cert mitbringt und man versucht dies mit openssl zu verifizieren und wenn das nicht klappt, weiß man das keine brauchbaren root CAs konfiguriert sind
