### ISSUE TITLE
Composer phar is not rendered by php on package management page of Contao

### ISSUE THREAD

**Issue by grandgeorg** [contao-community-alliance/composer-client#263]
We have Contao 3.5 installed with contao-community-alliance/composer-client 0.15.2 in our production enviroment (hosteurope). We have PHP Suhosin Executor Include Whitelist set to phar. The probelm is that the composer.phar file is not rendered by php, but included and treated as a text only file. So on the package management page of Contao the source content of composer.pahr is displayed in the html body of the page. Look at the screenshot to see what I mean. We also checked the server with Contao check (https://github.com/contao/check) there everything is ok.
![capture_24092015_200154](https://cloud.githubusercontent.com/assets/811894/10082129/85b0cdb4-62f8-11e5-84b2-a366a6e97361.jpg)

**Comment by Toflar** [comment]
Try setting
```ini
detect_unicode = Off
```

in your `php.ini` settings.

**Comment by grandgeorg** [comment]
Thanks this seems to be the hint in the right direction. But unfortunately it does not help. PHP Version on the server is 5.5.29-1~he.1 and (in phpinfo) there is a setting called zend.detect_unicode, which for the local value I managed to turn off (by placing 'php_value zend.detect_unicode Off' in htaccess file). But that does not help. There is no setting called just detect_unicode (without zend) in this php settings. Unfortunately at hosteurope (with shared hosting package) you can not edit php.ini directly. Maybe this setting has also to set for CLI PHP?

**Comment by grandgeorg** [comment]
Now it works - the problem was (I think) that php had no write permission to composer/composer.phar. I changed that, then Contao in the package manager told me that composer has been updated (how and why?) and since then everything works fine. - Strange - Anyways thanks a lot for help and sorry for bothering you.
