### ISSUE TITLE
SWGlossar cannot be found in contao-legacy

### ISSUE THREAD

**Issue by fritzmg** [contao-community-alliance/composer-client#267]
When searching for [SWGlossar](https://contao.org/de/erweiterungsliste/view/SWGlossar.de.html), no search result is returned. It seems the extension is generally not available via the contao-legacy repository.

**Comment by Toflar** [comment]
Dürfte daran liegen, dass die kommerziell ist.

**Comment by fritzmg** [comment]
Ah stimmt, ist mir bisher nicht aufgefallen.

**Comment by Toflar** [comment]
Dann darf das Ticket wohl geschlossen werden ;)
