### ISSUE TITLE
PHP Version from server wrong interpreted

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [contao-community-alliance/composer-client#268]
I got this Message:
  Problem 1
    - Installation request for contao-community-alliance/composer-client dev-master -> satisfiable by contao-community-alliance/composer-client[dev-master].
    - contao-community-alliance/composer-client dev-master requires php >=5.3.4 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
  Problem 3
    - contao-community-alliance/composer-client 0.15.4 requires php >=5.3.4 -> your PHP version (5.3.3) or 

But my PHP-Version is 5.4.45.
Server Linux af92e 2.6.32-504.23.4.el6.x86_64 #1 SMP Tue Jun 9 20:57:37 UTC 2015 x86_64

How can I fix this?
Where ist this file "config.platform.php", please ?

**Comment by tim-bec** [comment]
Schau mal ob deine Command-Line php Version die gleiche ist wie ein phpinfo(); dir ausgibt

**Comment by MoniqueHahnefeld** [comment]
shit, wieso steht da "PHP Version => 5.3.3"
Hat das was mit der "plattform"-Einstellung zutun. Habe da folgendes gefunden:
https://github.com/composer/composer/issues/4243
??
Danke aber schonmal :)

**Comment by MoniqueHahnefeld** [comment]
Ich habe das hier probiert und es hat nichts geholfen. Daher geh ich mal davon aus das es an den Servereinstellungen liegt ...
php composer.phar --ignore-platform-reqs install
https://getcomposer.org/doc/03-cli.md#install
