### ISSUE TITLE
Since Contao 2 support was removed, you can remove the ER2 extension check for rep_* modules

### ISSUE THREAD

**Issue by backbone87** [contao-community-alliance/composer-client#269]
https://github.com/contao-community-alliance/composer-client/blob/master/src/system/modules/!composer/src/Client.php#L80

i think these are only Contao 2 modules

**Comment by discordier** [comment]
Yep, thanks for notifying.

**Comment by discordier** [comment]
Has been resolved with 56ea484414bcf0c68762bfd8a1be5beaea88da42
