### ISSUE TITLE
Contao 4 module - mark conflict

### ISSUE THREAD

**Issue by comolo** [contao-community-alliance/composer-client#270]
Could you add a feature, that the composer-client marks branches and versions that conflict with the contao/core as a conflict. That would be nice.

Reason: My contao module has a version which is only compatible with Contao 4. I want to make sure, it´s not possible to install it with Contao 3.

![bildschirmfoto 2015-11-26 um 21 14 38](https://cloud.githubusercontent.com/assets/1228676/11430162/c16a5670-9482-11e5-9972-4a7536686d1f.png)

**Comment by discordier** [comment]
What does the dependency of this project have to do with your module? Are you depending on the composer-client instead of the composer-plugin?
