### ISSUE TITLE
Text Output-Box wird nicht angezeigt

### ISSUE THREAD

**Issue by 31er** [contao-community-alliance/composer-client#271]
Contao 3.5.6 und Composer-Client 0.16.2

Die schwarze Infobox wird nicht mehr angezeigt wenn man auf den Button „Testlauf“ oder „Pakete aktualisieren“ klickt.

Siehe auch https://community.contao.org/de/showthread.php?60576-Paketverwaltung-Infobereich-erscheint-nicht

**Comment by fritzmg** [comment]
I can confirm this problem. After letting the composer-client update the composer.phar to the newest version, there will be nothing written into the `composer.out` file anymore (thus nothing is displayed in the backend).

**Comment by bizon1** [comment]
Same here, I also got an empty composer.out after updating the composer.phar.
And the same problem when I did a new contao-3.5.6 and composer installation.

**Comment by discordier** [comment]
Which mode do you use?
Standalone or embedded?

**Comment by 31er** [comment]
Wo sehe ich das welcher Mode es ist?
Unter Contao Einstellungen und Paketverwaltung Einstellungen finde ich nichts mit Standalone oder Embedded? Es sind eigentlich die Default-Einstellungen von der Erstinstallation bei mir gesetzt.

Einstellungen Paketverwaltung
Minimale Stabilität: Entwicklerversion
Bevorzugte Installationsart: Distributionsarchiv
Änderungen verwerfen: lokale Änderung behalten (Update anhalten)
Stabile bevorzugen: Ja, Haken gesetzt

Einstellungen Contao
Composer Bibliothek automatisch aktualisieren: Ja, Haken gesetzt
Ausführlichkeiten der Protokollierung: Standard Ausführlichkeit
Extension Repository Tabellen löschen: Nein, kein Haken gesetzt

**Comment by discordier** [comment]
In den Einstellungen von Contao unter "Composer" findest du "Execution mode" (Such dir die dt. Ybersetzung bitte selbst raus).
- In the HTTP request.
- as sub process of the web server process
- as standalone process

**Comment by bizon1** [comment]
I'm using the mode: In the HTTP request - that's the default setting.

**Comment by 31er** [comment]
Ist auf "während der aktuellen http-Anfrage" gesetzt.

**Comment by fritzmg** [comment]
It does not happen in `process` or `detached` mode as far as I have tested, only in `inline` mode. To reproduce, simply update the `composer.phar` to the newest version and set `composerExecutionMode` to `inline`.

**Comment by xantippe** [comment]
bei mir auch nicht :-(
contao-community-alliance/composer-client 0.16.2

**Comment by discordier** [comment]
Please test with febb097 in the hotfix branch so we can release asap.

**Comment by 31er** [comment]
Habe dev-hotfix/various-issues (023ef728) installiert und bei mir ist die Textoutputbox wieder da.
Vielen Dank für die Bemühungen.

**Comment by kikmedia** [comment]
Works for me, thanks a lot.

**Comment by bizon1** [comment]
Works for me too,  Great job thanks

**Comment by cliffparnitzky** [comment]
Works for me. Thanks.

**Comment by UlrichHolland** [comment]
Works for me too, thanks!

**Comment by fritzmg** [comment]
The "Testrun" and "Update packages" buttons on the bottom left instead of the bottom right in the hotfix branch. I am guessing that's not intended.

**Comment by discordier** [comment]
What browser?

**Comment by UlrichHolland** [comment]
Mozilla Firefox 44.0 for Ubunu canonical 1.0

**Comment by discordier** [comment]
I was referring to @fritzmg because of the buttons. They are where they belong on my machine.
Can anyone confirm that they are misplaced?

**Comment by UlrichHolland** [comment]
Yes, i do confirm, they are misplaced ...

**Comment by bizon1** [comment]
i saw this twice when I was testing your dev-hotfix/various-issues in two different contao projects. Just after the package update ends both buttons were on the left side. After reloading the page the buttons have moved back to the right, so for me their wasn't any reason to think about it longer.
Browser: Pale Moon

**Comment by fritzmg** [comment]
`style="float:left"` is missing on `#tl_composer_search`

**Comment by fritzmg** [comment]
Styles for `.composer_warn` also seem to be missing.

**Comment by discordier** [comment]
It is definitely in above commit, both of the styles are contained in the scss and css files.
Don't know what's going wrong on your side here...
Could it be that the files in `/system/modules/!composer` have not been updated on your side or that the css file is fetched from browser cache instead of the server?

**Comment by MacKP** [comment]
@fritzmg I have no problem with the buttons. Looks the same as before.. (Mozilla Firefox 44.0 for Kubuntu canonical 1.0)
regards

**Comment by UlrichHolland** [comment]
@discordier
You are right, guess that the css file was fetched from browser cache, now it works, thanks!

**Comment by fritzmg** [comment]
Ah, same here, sorry for the confusion :)

**Comment by vgt1920** [comment]
**@discordier**
grosses dankeschoen, schwarze Testbox wieder da, habe einfach komplettes Verzeichnis \!composer erneuert
