### ISSUE TITLE
contao sources are not removed when uninstalling a package

### ISSUE THREAD

**Issue by fritzmg** [contao-community-alliance/composer-client#272]
When uninstalling a package, the folders defined under
```
	"extra":{
		"contao":{
			"sources":{
				…
			}
		}
	}
```
are currently not deleted. All the files within are deleted, however the folder and all its subfolders remain.

* Linux / Debian 7
* PHP 5.6
* Contao 3.5.6
* composer-client 0.16.2

**Comment by discordier** [comment]
Could not reproduce so far. Anyone else?
btw. this is a bug in the composer-plugin rather than the client.

**Comment by fritzmg** [comment]
> Could not reproduce so far. Anyone else?

Hm, so far it only happened on that one Linux system, I wasn't able to reproduce it anywhere else either.

> btw. this is a bug in the composer-plugin rather than the client.

Ah, yeah I wasn't sure, sorry.

**Comment by fritzmg** [comment]
I think the composer-plugin didn't delete the directories because they were not empty. There were hidden SVN files. Can be marked as invalid.
