### ISSUE TITLE
Contao-Legacy Pakete nicht mehr verfügbar

### ISSUE THREAD

**Issue by fenepedia** [contao-community-alliance/composer-client#277]
Hallo,

ich habe seit ein paar Tagen bei mehreren Installationen festgestellt, dass sich keine alten Pakete mehr installieren lassen.
Das betrifft alle Pakete die mit Legacy gekennzeichnet sind.

Beispiel: "Kein Treffer für contao-legacy/backupdb gefunden!"

Viele Grüße
Christian

**Comment by fritzmg** [comment]
Ja, hatte mich auch schon gewundert, hat mich gestern Abend und heute schon einige Nerven gekostet, weil ich mich wundere was ich falsch mache ;). Ich bekomme auch

- bei egal welchem package
- auf egal welchem Betriebssystem
- egal welcher PHP Version (getestet mit 5.3.x, 5.5.x und 5.6.x)

immer die Meldung
```
The requested package contao-legacy/… could not be found in any version, there may be a typo in the package name.
```
Bereits zuvor installierte `contao-legacy` Pakete beanstandet der Composer nicht.

Getestet immer direkt über die command line.

**Comment by BlackP999** [comment]
HI, ich habe das selbe Problem

**Comment by backbone87** [comment]
klingt so als wäre der ER2-Composer proxy nicht mehr lauffähig

**Comment by discordier** [comment]
Das Problem sollte behoben sein.

Ursaechlich war ein Softwareupdate des Packagist servers.
Dieser behielt zwar seine komplette Funktion hinsichtlich Paketsuche und Import aus dem ER2, jedoch das erzeugen der statischen Datendumps (package.json) war hiernach fehlerhaft.

Ich habe den Fehler nun nach langer Suche eingrenzen koennen und behoben. Bei mir geht nun wieder alles.

Sorry fyr die Umstaende.

**Comment by cliffparnitzky** [comment]
Top. Läuft alles wieder. Danke.

**Comment by fenepedia** [comment]
Läuft wieder einwandfrei! Vielen Dank.
