### ISSUE TITLE
Composer removes path to Contao

### ISSUE THREAD

**Issue by seaneble** [contao-community-alliance/composer-client#280]
Every time I access the backend module for Composer in a Contao 3.5.6 installation, the frontend of the websites turns into to an error page:

    Warning: include(/…/htdocs/composer/vendor/contao/core/system/modules/core/modules/ModuleArticle.php): failed to open stream: No such file or directory in
    system/modules/_autoload/library/Composer/Autoload/ClassLoader.php

As far as I traced the problem, there should be a (symbolic) link from the vendor directory to the Contao root. If I recreate this, the frontend works fine:

    mkdir composer/vendor/contao
    ln -s ../../../ composer/vendor/contao/core

But: this does not fix the situation permanently, every time somebody opens the Composer view in Contao, the website breaks.

This would be a rather major bug if everybody would be affected. But it seems that nobody has the same trouble, at least I don't hear loud screams. So, why does this happen to this setup? How would I fix it permanently?

**Comment by discordier** [comment]
You should not have a core in vendor/contao/core... please check that you have the latest plugin, delete the vendor/contao/core directory, perform composer update and check that it will NOT recreate said folder.

Previous plugin versions had an issue that the core could get installed on plugin updates.
This has been fixed with composer-plugin 2.4

**Comment by discordier** [comment]
@seaneble any update? Otherwise I'd close it.

**Comment by seaneble** [comment]
I will try this asap. But I don't think it will help, as the directory has not been created. I had to create it as a symlink in order to make the Autoloader work again. So the issue should be elsewhere.

**Comment by seaneble** [comment]
I used the CLI to perform a Composer selfupdate and an update of all packages. Now it works. Weird, anyway. Thanks for your help!

**Comment by niebuhrhood** [comment]
Hi guys,

same problem in two different installations, when updating from

Contao 3.4 to 3.5.6
Composer 0.16.3

`Warning: include(/html/paychex-contao-356/composer/vendor/contao/core/system/modules/core/library/Contao/InsertTags.php): failed to open stream: No such file or directory in system/modules/_autoload/library/Composer/Autoload/ClassLoader.php on line 363`

`Warning: include(): Failed opening '/html/paychex-contao-356/composer/vendor/contao/core/system/modules/core/library/Contao/InsertTags.php' for inclusion (include_path='.:/usr/local/php/lib/php:/usr/local/php/lib/php/PEAR') in system/modules/_autoload/library/Composer/Autoload/ClassLoader.php on line 363`

Composer is updated in settings. 
How can I manage a manual update over Terminal?

**Comment by discordier** [comment]
Try to run:
```shell
user@nowhere:~$ cd TL_ROOT/composer
user@nowhere:TL_ROOT/composer$ COMPOSER_HOME=`pwd` php composer.phar update
```

**Comment by niebuhrhood** [comment]
Thanks, but Im running into:
'Warning: Composer should be invoked via the CLI version of PHP, not the cgi-fcgi SAPI'

So I can't run this in Php 5.5.21 CGI?

**Comment by niebuhrhood** [comment]
Actually I can't install php-cli on a managed server.
