### ISSUE TITLE
Your configuration does not allow connection to http://legacy-packages contao

### ISSUE THREAD

**Issue by 31er** [contao-community-alliance/composer-client#281]
Contao 3.5.6
Composer-Client 0.16.3

Bei "Testlauf" oder "Pakete aktualisieren" erscheint im Textoutput:
`Your configuration does not allow connection to http://legacy-packages-via.contao-community-alliance.org. See https://getcomposer.org/doc/06-config.md#secure-http for details.
http://legacy-packages-via.contao-community-alliance.org could not be fully loaded, package information was loaded from the local cache and may be out of date`

Der Hinweis verschwindet erst, wenn man in der composer.json http auf https ändert.
Siehe auch: [https://community.contao.org/de/showthread.php?61453-Your-configuration-does-not-allow-connection-to-http](url)

**Comment by fritzmg** [comment]
This happens with the recent `composer.phar` update. composer does not allow unsecure connections by default anymore:

> secure-http#
>
> Defaults to true. If set to true only HTTPS URLs are allowed to be downloaded via Composer. If you really absolutely need HTTP access to something then you can disable it, but using Let's Encrypt to get a free SSL certificate is generally a better alternative.

https://getcomposer.org/doc/06-config.md#secure-http

However, even if you have both versions (`http` and `https`) of the contao legacy package repository in the `repositories` section of your `composer.json`, composer will still complain. The only solution is to remove
```
{
    "type": "composer",
    "url": "http://legacy-packages-via.contao-community-alliance.org/"
}
```
(or add `"secure-http": true` to the `config` section)

**Comment by discordier** [comment]
In fact there is no real reason IMO to still retain the `http` url in composer.json.
Most servers have `https` support now a days and therefore it is obsolete.

We can safely delete it.
However, this will only affect new installations then.

**Comment by MacKP** [comment]
Hab gerade bei einer Installation auf Composer gewechselt. Dabei noch zwei legacy Pakete belassen (efg und xls_export). Auch wenn ich die Zeilen aus der composer.json entfernt habe (ja, auch cache von Composer geleert) bin ich nicht weiter gekommen. Notlösung: legacy-Erweiterungen aus composer.json entfernen, dann update machen und Erweiterungen per Hand wieder hochladen. Dann Erweiterungen wieder in die composer.json eintragen, damit mir die nicht beim nächsten mal entfernt werden ^^
Scheint irgendwo noch der Wurm drinn zu sein oder?

Viele Grüße

**Comment by discordier** [comment]
Du hast in der composer.json den Bereich mit http:// entfernt?

**Comment by MacKP** [comment]
Ja, sowas von. Der war so weg, das ich den gar nicht mehr gesehen habe ;-)
Vorher hab ich den mal bearbeitet gehabt und https draus gemacht.
Beides hat nicht geholfen :(

**Comment by fritzmg** [comment]
Hm, have you tried deleting everything under `/composer/cache/repo` as well?

**Comment by MacKP** [comment]
Jep, everything in `/composer/cache`

**Comment by frontendschlampe** [comment]
I had the same problem but I just take out

`{
            "type": "composer",
            "url": "http://legacy-packages-via.contao-community-alliance.org/"
        }`

and everything works fine!

**Comment by christianbarkowsky** [comment]
Also the same problem.

Expertenmodus > s added > save > Composer Cache leeren  > nun geht's.

**Comment by frontendschlampe** [comment]
@christianbarkowsky Du musst es aber nicht hinzufügen, sondern eher den http Eintrag löschen, oder?!

**Comment by christianbarkowsky** [comment]
@frontendschlampe bei mir ging es aber so!

**Comment by frontendschlampe** [comment]
ja ... natürlich ging es, aber der Eintrag für https steht doch bereits drin!

**Comment by christianbarkowsky** [comment]
@frontendschlampe stimmt ... nun ist es doppelt! :-s

**Comment by frontendschlampe** [comment]
:-D ... sag ich doch!

**Comment by bytehead** [comment]
Legacy Pakete werden aber scheinbar immernoch über die HTTP-Verbindung geladen:
`  - Installing contao-legacy/newslanguage (2.1.0.9035)
Downloading http://legacy-packages-via.contao-community-alliance.org/er2-proxy/newslanguage/20010009/35`

trotz HTTPS in der `composer.json`:
 `{
            "type": "composer",
            "url": "https://legacy-packages-via.contao-community-alliance.org/"
}`

**Comment by fritzmg** [comment]
Lösche mal Cache, lock und installed file.

**Comment by bytehead** [comment]
Habe ich versucht, alles bis auf das `composer.json` file gelöscht - ohne legacy pakete gehts.

**Comment by bytehead** [comment]
I have set up a empty directory with the accordingly `composer.json` file and it still fails:
```bash
- Installing contao-legacy/newslanguage (2.1.0.9035)
Downloading http://legacy-packages-via.contao-community-alliance.org/er2-proxy/newslanguage/20010009/35
    Downloading: Connecting...    Download failed, retrying...
Downloading http://legacy-packages-via.contao-community-alliance.org/er2-proxy/newslanguage/20010009/35
    Downloading: Connecting...    Download failed, retrying...
Downloading http://legacy-packages-via.contao-community-alliance.org/er2-proxy/newslanguage/20010009/35
    Downloading: Connecting...
Failed: [Composer\Downloader\TransportException] 0: Your configuration does not allow connection to http://legacy-packages-via.contao-community-alliance.org. See https://getcomposer.org/doc/06-config.md#secure-http for details.

                                                                                                                                                                                   
  [Composer\Downloader\TransportException]                                                                                                                                         
  Your configuration does not allow connection to http://legacy-packages-via.contao-community-alliance.org. See https://getcomposer.org/doc/06-config.md#secure-http for details.
```

**Comment by fritzmg** [comment]
Could it be, that the contao-legacy packagist server actually points to the er2-proxy repositories _without_ SSL, regardless of whether you use https://legacy-packages-via.contao-community-alliance.org or http://legacy-packages-via.contao-community-alliance.org ?

**Comment by bytehead** [comment]
It seems to be like this...

**Comment by discordier** [comment]
Yep, that's the case.
Sadly the complete re-import of all extensions is still running.

When it is done, all URLs will be https:// based

**Comment by bytehead** [comment]
thanks! :+1:

**Comment by discordier** [comment]
All parsed, new URLs should be distributed as caches slowly clear up.
Any update on your side?

**Comment by bytehead** [comment]
Works for me!

**Comment by monofone** [comment]
After cleaning up the composer.json the composer stuff is working. So for me it`s working too, but I haven`t installed any extensions, just searched and detail views.

**Comment by k-webdesign** [comment]
Läuft

**Comment by discordier** [comment]
Fixed in trunk with c247028160499cc9c3eadaf0f5fe5aeaa897fd56.

**Comment by fritzmg** [comment]
Since this will affect everyone that tries to make a fresh composer client installation, `0.16.4` should be released as soon as possible.

**Comment by discordier** [comment]
Granted, I just wanted to wait for input on all other issues. Mainly on the endless loop of "restart the operation". However I suspect it was due to the regression introduced in composer 1.0.1 and fixed in 1.0.2.
Will release within the next days.

**Comment by anneyonghaseo** [comment]
just a note: we still need the http version for testing out satis in our local computer

**Comment by paulocastroo** [comment]
just a note: we still need the http version for testing out satis in our local computer

**Comment by discordier** [comment]
Can you clearify this? Why do you want to connect via plain http instead of https?
I thought satis knows HTTPs.

**Comment by planktonfun** [comment]
When you use satis server on your local computer (not hosted in a domain) and a self-signed certificate
 it wouldn't work even if you add the option verify peer false e.g. https://localhost:8181,

 but luckily adding '"secure-http":false' under options key inside composer.json will work 
but not recommended according to composers documentation

**Comment by flik** [comment]
You can run the command and get fix: 

`composer config -g secure-http false`

**Comment by fritzmg** [comment]
@flik this is not recommended

**Comment by leonhoffmann86** [comment]
Simply add this configuration to your composer.json file.

"config": {
"secure-http": false
}
Here is an full example of a working composer.json file

  "repositories": [{
    "type": "composer",
    "url": "http://packagist.org"
  }],
  "require": {
    "phpmailer/phpmailer": "^6.0"
  },
  "config": {
    "secure-http": false
  }
}
```

**Comment by fritzmg** [comment]
@leonfrombeawwwer you should __not__ do this.

**Comment by leonhoffmann86** [comment]
@fritzmg Thanks for the feedback. Would you explain why? Thanks, Leon

**Comment by fritzmg** [comment]
The real solution for any SSL problem is _never_ to not use SSL, as this is a potential security risk. You should solve the SSL problem in the first place.

See all the comments above.

**Comment by leonhoffmann86** [comment]
I see, I was looking for ways to solve it but needed to move on with the project. As a quick fix it worked great for me. I can always remove the config and all will be secure again here, or not?
