### ISSUE TITLE
Can only install legancy packages.

### ISSUE THREAD

**Issue by t-me** [contao-community-alliance/composer-client#282]
Hello,

when i want to install or update packeges i get an blank screen on : https://www.domain.org/beta/mijn/contao/main.php?do=composer

When i check my hosting logs this shows up.

```
[Sat Mar 05 17:27:55 2016] [error] [client **.**.**.**] [host www.domain.org] Error receiving response header (lsphp is killed?): ReceiveResponseHeader: receive pkg hdr failed: ReceiveLSHeader: nothing to read from backend socket, referer: https://www.domain.org/beta/mijn/contao/main.php?do=composer
```

When i try to install it with SSH composer returns wit killed.

I can only install contao-legacy packages now not other packages. 

Contao check returns all oke.
I have 2 contao installs both with the same problem.
Contao 3.5.8 -> Client 0.16.2
Contao 3.5.6 -> Client 0.16.3

My composer config :

``` json
{
    "name": "local/website",
    "description": "A local website project",
    "type": "project",
    "license": "proprietary",
    "require": {
        "cgo-it/rate-it": ">=3.5.1.0,<3.6-dev",
        "cliffparnitzky/birthday-mailer": "dev-master",
        "cliffparnitzky/extended-member-inserttags": ">=2.0.2.0,<2.1-dev",
        "codefog/contao-cookiebar": "^1.1",
        "components/bootstrap": ">=3.3.6.0,<3.4-dev",
        "contao-community-alliance/composer-client": "~0.12",
        "contao-legacy/rateit": ">=3.5.1.9004,<3.6-dev",
        "netzmacht/contao-font-awesome": ">=4.5.0.0,<4.6-dev",
        "terminal42/contao-avatar": ">=1.1.0.0,<1.2-dev",
        "terminal42/contao-mailusername": ">=1.0.5.0,<1.1-dev"
    },
    "prefer-stable": true,
    "minimum-stability": "dev",
    "config": {
        "preferred-install": "dist",
        "cache-dir": "cache",
        "component-dir": "../assets/components"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://legacy-packages-via.contao-community-alliance.org/"
        },
        {
            "type": "artifact",
            "url": "packages"
        }
    ],
    "extra": {
        "contao": {
            "migrated": "done"
        }
    }
}
```

**Comment by discordier** [comment]
For the error:  
```
Error receiving response header (lsphp is killed?): ReceiveResponseHeader: receive pkg hdr failed: ReceiveLSHeader: nothing to read from backend socket
```
You get this because the composer execution simply takes too long to complete for your fastcgi handler. Nothing we can do on our side here. Try with the "detached mode".

For your statement:
> When i try to install it with SSH composer returns wit killed.

I do not understand what you mean. How can something return with "killed"? Do you have any console transcript? I need more details here.

> I can only install contao-legacy packages now not other packages.

This is pretty strange, you should not be able to install anything or everything. There is no difference of legacy packagages to "real" packages aside from the download method.
Therefore it could now be your oauth token (if configured), your git installlation (when installing from source or no oauth configured) and many other things causing hicups here.
Yet again, do you have logs and or console transcripts you could provide us with?

**Comment by t-me** [comment]
Really strange indeed that I can install legency packages but not other packages.
But found out that it was a memory issue, composer uses a lot of memory.

Found out that composor needs sometimes 1gb or more on memory why i have no clue.

Is there a check that can be build in that looks if the memory is less than 1GB and then returns a warning that says that it the process may be interrupted by the memory limit?

**Comment by discordier** [comment]
The amount of memory needed is in correlation to the amount of installation candidates.
Therefore, the more extensions you have installed, the more memory is needed to calculate the best matching set of versions.
You can lower the amount of needed memory by specifying a minimum stability of "stable" in the settings.

For defining a warning message, we can not do this as we simply have no idea how much memory will be needed in advance. Therefore this message would never be accurate at all.
