### ISSUE TITLE
suggestion: update composer.phar only when necessary

### ISSUE THREAD

**Issue by fritzmg** [contao-community-alliance/composer-client#284]
Just a thought: many or at least some of the recent (temporary) problems were caused by updates to the `composer.phar` - may be it would be better, if the `composer.phar` is not auto-updated by default, but gets auto-updated by the `composer-client` whenever necessary? 

This way, you can react to changes within `composer`, release a client update and _then_ let it update the `composer.phar` - thus preventing the users from running into any issues.

However this of course means, that the developers have to periodically check for composer updates and check whether those cause any problems.

**Comment by discordier** [comment]
The problem here is, that when we say "update composer now" there might have additional changes again which break the system.
This is due to the fact, that composer is still in alpha stage and does not tag the alpha releases that often. Therefore you can only get the "current" release phar as download, which ever this "current" is referring to at the time downloading might be.
Therefore your suggestion will only work in some cases but will break for others again

**Comment by fritzmg** [comment]
True. Well, instead of auto-updating the `composer.phar` at all, why not distribute a `composer.phar` with the `composer-client` that is known to work? Thus, whenever an update to the `composer.phar` is necessary or vital, you update that in the `composer-client` and create a new release. If users need to update their `composer.phar` immediately due to a known issue, and the update is known to not cause any problems with their current `composer-client` version (or at least problems are not expected), then they can still manually update (though the `composer.phar` would get potentially overwritten with an older version during the next `composer-client` update - then they would have to run the update again).

**Comment by discordier** [comment]
This will force us to release a new version of the client every few days.
This means:
* pushing a new composer.phar to the repo (bloating that one with a big junk of binary data of almost no use).
* tagging the new release as patchlevel (we will end up with 0.16.4800 pretty quickly)
* uploading the very same to the ER2 (as this has to be distributed over there as well for migration reasons).
  * logging into ER2
  * creating new version there
  * importing the new tag.
  * editing the change log (in all languages)
  * publishing the new version.

This all in all takes a lot of time, can not be automated and provides only minor benefit.
Therefore I really don't think we will do this, sorry.

**Comment by fritzmg** [comment]
> This will force us to release a new version of the client every few days.

Not really. Not every `composer.phar` update is essential. But every `composer.phar` update bears the risk that it might break the functionality of either the `composer-client` or the `composer-plugin`. For the sake of regular users, who are bombarded with warning messages all of a sudden and have no experience about what should be done, it would be better to stay in a stable environment.

**Comment by discordier** [comment]
The only thing I could live with, regarding this, is to disable the periodic auto update and the user will then have to update `composer.phar` manually.

Periodically pushing a `composer.phar` is out of the question due to above mentioned limitations.
We maybe (big maybe here) could add a `composer.phar` to the ER, so people have a consistent file when installing a new Contao instance. From there on they are then responsible for updating it on their own (have to talk to @frontendschlampe on this one, as he is the one maintaining the ER2).

@contao-community-alliance/members Any input from you guys?

**Comment by fritzmg** [comment]
Yeah, disabling the auto-update and providing a known-to-work `composer.phar` in the ER2 sounds good to me :+1:

**Comment by fritzmg** [comment]
Btw. on that note: may be the `composer-client` should create a backup of the current `composer.phar` before executing the `self-update`. This way users could more easily switch back, if something goes wrong with the new version.

**Comment by discordier** [comment]
The default config value of the auto update of composer.phar has been changed with eac822d022f53f649d93eb5adeedef3b43469cad.

The deployment of a "working" composer.phar into the ER2 will have to be done by @frontendschlampe  when publishing 0.16.4

**Comment by fritzmg** [comment]
But then you should also remove this: https://github.com/contao-community-alliance/composer-client/blob/0.16.3/src/system/modules/!composer/src/ClientBackend.php#L105
```php
// do install composer library
if ($input->post('install')) {
    $this->updateComposer();
    $this->reload();
}
```
or better, change it, so that it only downloads the `composer.phar`, if it is not already present.

**Comment by discordier** [comment]
You have had a look on line 99?
```php
        // check composer.phar is installed
        if (!file_exists(COMPOSER_DIR_ABSOULTE . '/composer.phar')) {
            // switch template
            $template = new \BackendTemplate('be_composer_client_install_composer');
            // do install composer library
            if ($input->post('install')) {
                $this->updateComposer();
                $this->reload();
            }
            return $template->parse();
        }
```
It is already being checked. If not present, we check if "install" has been clicked and if so, THEN we download.
There is no need to check again if it is present as there is virtually no way that you upload it by hand between the execution of the two "if"s. :smile:

**Comment by fritzmg** [comment]
Oh, missed that :)

**Comment by fritzmg** [comment]
Careful: even if you set
```php
$GLOBALS['TL_CONFIG']['composerAutoUpdateLibrary'] = false;
```
the `composer-client` will currently __still__ auto-update the `composer.phar` depending on `Runtime::readComposerDevWarningTime()` as mentioned [here](https://github.com/contao-community-alliance/composer-client/issues/288#issuecomment-209461583).

**Comment by fritzmg** [comment]
The ER2 release of the composer-client does not include a stable `composer.phar`. Was this idea dropped?

**Comment by frontendschlampe** [comment]
no ... it will come in future versions ... actually it's just possible via console

**Comment by fritzmg** [comment]
This has become important again due to #300.

**Comment by discordier** [comment]
I assume you are referring to:

> The ER2 release of the composer-client does not include a stable composer.phar. Was this idea dropped?

Or how has this become important again?

**Comment by fritzmg** [comment]
Yes, I meant the inclusion of the composer.phar

**Comment by discordier** [comment]
That is up to @frontendschlampe to add.
Nothing to do for me here, however, it would have to get updated on a regular basis then.
