### ISSUE TITLE
CaBundleWorkaround leads to fatal error with new composer.phar

### ISSUE THREAD

**Issue by fritzmg** [contao-community-alliance/composer-client#288]
With the newest `composer.phar` and `composer-client` `0.16.3` the following error happens when accessing the package management in the backend:
```
[13-Apr-2016 15:23:28 Europe/Vienna] PHP Fatal error: Uncaught exception 'BadMethodCallException' with message 'Entry res/cacert.pem does not exist' thrown in …/system/modules/!composer/src/Util/CaBundleWorkaround.php on line 65
#0 …/system/modules/!composer/src/Util/CaBundleWorkaround.php(65): Phar->offsetGet('res/cacert.pem')
#1 …/system/modules/!composer/src/Runtime.php(531): ContaoCommunityAlliance\Contao\Composer\Util\CaBundleWorkaround::setCaFileIfOpenBaseDirInUse(Object(Phar))
#2 …/system/modules/!composer/src/ClientBackend.php(290): ContaoCommunityAlliance\Contao\Composer\Runtime::registerComposerClassLoader()
#3 …/system/modules/!composer/src/ClientBackend.php(125): ContaoCommunityAlliance\Contao\Composer\ClientBackend->loadComposer()
#4 …/system/modules/core/classes/Backend.php(262): ContaoCommunityAlliance\Contao\Composer\ClientBackend->generate()
#5 …/contao/main.php(137): Contao\Backend->getBackendModule('composer')
#6 …/contao/main.php(288): Main->run()
#7 {main}
```
This will probably affect a lot more installations soon, as more `composer.phar` files get auto-updated.

**Comment by fritzmg** [comment]
The CAFile was removed in this commit: https://github.com/composer/composer/commit/592374ea937322b97bb885b673e6b1443fc02604
It is still present in the `1.0.0` release though: https://github.com/composer/composer/blob/1.0.0/res/cacert.pem

**Comment by fritzmg** [comment]
This issue cannot be easily worked around either. Even if you set
```php
$GLOBALS['TL_CONFIG']['composerAutoUpdateLibrary'] = false;
```
in your `localconfig.php` and download the [1.0.0 release of the composer.phar](https://getcomposer.org/download/1.0.0/composer.phar), the `composer-client` will __still__ auto-update the `composer.phar` to the latest snapshot, because `!$composerDevWarningTime` will be true in this condition:
```php
if (!$composerDevWarningTime
    || $GLOBALS['TL_CONFIG']['composerAutoUpdateLibrary']
       && ($incompatibleVersion || time() > $composerDevWarningTime)
) {
    Runtime::updateComposer();
    Messages::addConfirmation($GLOBALS['TL_LANG']['composer_client']['composerUpdated']);
}
```
https://github.com/contao-community-alliance/composer-client/blob/0.16.3/src/system/modules/!composer/src/ClientBackend.php#L270

So to actually work around it, you have to manually disable those lines of code.

**Comment by fritzmg** [comment]
There is actually a new package called [`composer/ca-bundle`](https://github.com/composer/ca-bundle) now. It provides the following methods:
```php
CaBundle::getSystemCaRootBundlePath() // auto detect, returns either system or bundled ca file
CaBundle::getBundledCaBundlePath() // returns bundled ca file
```
https://github.com/composer/composer/pull/5177#issuecomment-208416720

**Comment by fritzmg** [comment]
hofix/0.16.4 seems to work fine on tested affected systems

**Comment by Olli** [comment]
With hotfix/0.16.4 I got
                                                                                                                                    
```
  [ContaoCommunityAlliance\Composer\Plugin\DuplicateContaoException]                                                                             
  Warning: Contao core was about to get installed but has been found in project root, to recover from this problem please restart the operation  

```

**Comment by fritzmg** [comment]
Did you do what the warning said? i.e. start the composer update again? 

Or are you stuck in an infinite update loop? I got the same problem once with `hotfix/0.16.3`: #278

**Comment by fritzmg** [comment]
@Olli download [composer 1.0.2](https://getcomposer.org/download/1.0.2/composer.phar) and copy to `/composer`, then try to run the composer update again and see if that fixes the update loop.

**Comment by Olli** [comment]
Did fix nothing. I got the same error (https://github.com/contao-community-alliance/composer-client/issues/288#issuecomment-211278833).
10 times starting update doesn't help. I got this error on console.

**Comment by Floxn** [comment]
get another error with hotfix/0.16.4 and composer 1.0.2 phar:

> Fatal error: Uncaught exception 'PharException' with message '__HALT_COMPILER(); must be declared in a phar' in /xxx/contao/update.phar.php:22 Stack trace: #0 /xxx/contao/update.phar.php(22): Phar::webPhar('update.phar.php', 'index.php', '', Array, 'phar_rewrite') #1 {main} thrown in /xxx/contao/update.phar.php on line 22

**Comment by fritzmg** [comment]
@Floxn when exactly do you get that error?

**Comment by Floxn** [comment]
when i start the live update

**Comment by fritzmg** [comment]
The Live Update? Do you mean the composer update? i.e. when you click on "Update packages"?

**Comment by Floxn** [comment]
yes the live update

**Comment by Floxn** [comment]
got the error of your first post on live update, too

**Comment by fritzmg** [comment]
Sorry, I am still confused. The contao live update is something completely different. Are you refering to "Update packages" in the "Package management"?

**Comment by Floxn** [comment]
Oh Sorry, just mixed up the composer and live update.

**Comment by Creasign** [comment]
Hi. The hotfix is working fine at the beginning, but sooner or later I have the same problems again. I think after "legacy packages repository was added to root composer.json" it stops working. It stops working, when I migrate extensions or I want to install a package.
Fresh installation of the hotfix on a fresh Contao 3.5.12. I have the same error mentioned in the opening thread.

**Comment by discordier** [comment]
Are you sure you get the exact same error?
Did you upgrade and by accident therefore then downgraded the composer-client from hotfix back to 0.16.3?

**Comment by Creasign** [comment]
Yes, based ob the error.log. I had the same idea of a downgrade, but how can i check this why could this happen?

**Comment by Olli** [comment]
Thanks - works fine. :)
