### ISSUE TITLE
use stable version of composer.phar

### ISSUE THREAD

**Issue by fritzmg** [contao-community-alliance/composer-client#289]
The `composer-client` auto-downloads the `composer.phar` from https://getcomposer.org/composer.phar. Since the first stable version of composer [has been released a few days ago](https://github.com/composer/composer/releases), may be it would be better to switch the download to the stable version. Though I am not sure how always the most recent stable version could be obtained automatically.

Or, to bring back my point from #284, may be the `composer-client` should also release an update whenever an update to a newer composer version is necessary.

**Comment by discordier** [comment]
Currently I do not know any way of obtaining the latest available version of composer (aside from scraping the html of getcomposer.org/download).
If you have any ideas, any PR is welcome.

**Comment by fritzmg** [comment]
Yeah, I have no good idea yet. But maybe it's best to now simply stick with a specific stable release?

**Comment by backbone87** [comment]
Das composer selbstupdate bevorzugt stabile versionen, wenn ich mich nich irre.

**Comment by discordier** [comment]
Only in recent versions.
Therefore you have a problem when upgrading from an old (unstable) Version.
It will fetch the most recent build, which will later on prefer stable builds and therefore stick to itself AFAIR.
