### ISSUE TITLE
Question : How to install on contao 4?

### ISSUE THREAD

**Issue by t-me** [contao-community-alliance/composer-client#290]
Hello,
When i red the read me i don't know witch options i have for conao 4.
Is there a how to for contao 4?

Because system Requirements are : Contao 2.11.* or Contao 3.1.* or higher
or is this not for contao 4?

**Comment by bytehead** [comment]
Contao 4 is based on Symfony. It's basically a Symfony bundle and it doesn't need this composer-client.
The best way for you is to use [contao/standard-edition](https://github.com/contao/standard-edition).

**Comment by t-me** [comment]
OK Thanks, but can i install this plugin, and is so how can i do it?
Then i can do the most things in the back-end and not with command line :)

**Comment by fritzmg** [comment]
There is no `composer-client` for Contao 4. There is a standalone tool for package management in development though: http://tenside.org/

**Comment by bytehead** [comment]
If you're not familiar with the command line so far, it's better to stick to Contao 3.5.x until tenside is public available.

**Comment by discordier** [comment]
As noted by @bytehead and @fritzmg, tenside and therefore Contao (Package) Manager is in the works for Contao 4.
Please refer to the repository over there: https://github.com/contao/package-manager/
