### ISSUE TITLE
PHP Fatal error:  Call to undefined function ContaoCommunityAlliance\Contao\Composer\Controller\posix_kill()

### ISSUE THREAD

**Issue by fenepedia** [contao-community-alliance/composer-client#292]
Ich habe hier bei einer Installation die gleiche Fehlermeldung wie bereits im Ticket #276 diskutiert wurde.

Allerdings handelt es sich nicht um ein Windows-System, sondern um ein normales SharedHosting auf einem Linux-Server.

PHP-Version: 5.6
Contao: 3.5.15

Auf Rückfrage beim Hoster, ob bei PHP das posix_kill() aktiviert werden kann, bekam ich eine Absage.

Der Fehler tritt nur über die GUI auf.
D.h. als Workaround kann ich derzeit die Pakete über die Kommandozeile per composer aktualisieren und installieren.

Ist das posix_kill() zwingend nötig, oder könnte man das umprogrammieren?

**Comment by fritzmg** [comment]
Manche shared hoster deaktivieren außerdem auch `shell_exec()` und `exec()`, da bleibt einem leider auch nichts anderes über, als das Update über die Kommandozeile durchführen zu lassen.

**Comment by fenepedia** [comment]
Hab ich fast befürchtet. Dann werde ich das Ticket mal schließen.

**Comment by discordier** [comment]
Man kann es auch "umprogrammieren", doch dann brauchen wir weitergehende Rechte auf andere Dinge des systems, wie die proc table usw, damit wir einen normalen kill per `proc_open` machen koennen.
Es fyhren viele Wege nach Rom, doch die meissten werden von den hostern verbaut.
Wir myssten hierbei eine genaue feature detection machen welche Funktionen alle moeglich sind und welche nicht, dazu fehlt jedoch die Zeit und es ist zum Glyck bei den Meissten auch nicht notwendig. :smiley_cat: 
Der composer wird nie bei allen laufen koennen, leider.

**Comment by fenepedia** [comment]
Von dem Hoster (Mitten im Wald) dachte ich eigentlich dass das kein Problem sein müsste. Aber da wurde ich wohl nun eines besseren belehrt. Zum Glück läuft es wenigsten direkt über die Console.
