### ISSUE TITLE
Fatal error: Uncaught exception file could not be downloaded (HTTP/1.1 404 Not Found)

### ISSUE THREAD

**Issue by BugBuster1701** [contao-community-alliance/composer-client#294]
Bei bestimmten Suchbegriffen in der Paketverwaltung kommt es zum Fatal Error.
Contao 3.5.15
composer-client 	0.16.4
composer-plugin 	2.4.3
Suche nach Paketname "facebook", ergibt nach einiger Zeit:
```
Fatal error: Uncaught exception Composer\Downloader\TransportException with message The "https://legacy-packages-via.contao-community-alliance.org/p/contao-legacy/facebookconnect%241e11fef1fa65b09a4ce7c1b6803dfa8f7e62128d0f822a1580f8f3e50f64005c.json" file could not be downloaded (HTTP/1.1 404 Not Found) thrown in phar://composer/composer.phar/src/Composer/Util/RemoteFilesystem.php on line 355

#0 phar://composer/composer.phar/src/Composer/Util/RemoteFilesystem.php(101): Composer\Util\RemoteFilesystem->get('legacy-packages-via.contao-community-alliance.org', 'https://legacy-packages-via.contao-community-alliance.org/p/contao-legacy/facebookconnect%241e11fef1fa65b09a4ce7c1b6803dfa8f7e62128d0f822a1580f8f3e50f64005c.json', Array, NULL, false)
#1 phar://composer/composer.phar/src/Composer/Repository/ComposerRepository.php(646): Composer\Util\RemoteFilesystem->getContents('legacy-packages-via.contao-community-alliance.org', 'https://legacy-packages-via.contao-community-alliance.org/p/contao-legacy/facebookconnect%241e11fef1fa65b09a4ce7c1b6803dfa8f7e62128d0f822a1580f8f3e50f64005c.json', false)
#2 phar://composer/composer.phar/src/Composer/Repository/ComposerRepository.php(332): Composer\Repository\ComposerRepository->fetchFile('https://legacy-packages-via.contao-community-alliance.org/p/contao-legacy/facebookconnect$1e11fef1fa65b09a4ce7c1b6803dfa8f7e62128d0f822a1580f8f3e50f64005c.json', 'provider-contao-legacy$facebookconnect.json', '1e11fef1fa65b09a4ce7c1b6803dfa8f7e62128d0f822a1580f8f3e50f64005c', false)
#3 phar://composer/composer.phar/src/Composer/Repository/ComposerRepository.php(165): Composer\Repository\ComposerRepository->whatProvides(Composer\DependencyResolver\Pool, 'contao-legacy/facebookconnect')
#4 phar://composer/composer.phar/src/Composer/Repository/CompositeRepository.php(91): Composer\Repository\ComposerRepository->findPackages('contao-legacy/facebookconnect', NULL)
#5 system/modules/!composer/src/Controller/SearchController.php(105): Composer\Repository\CompositeRepository->findPackages('contao-legacy/facebookconnect')
#6 system/modules/!composer/src/Controller/SearchController.php(53): ContaoCommunityAlliance\Contao\Composer\Controller\SearchController->searchPackages(Array, 0)
#7 system/modules/!composer/src/ClientBackend.php(213): ContaoCommunityAlliance\Contao\Composer\Controller\SearchController->handle(Contao\Input)
#8 system/modules/core/classes/Backend.php(423): ContaoCommunityAlliance\Contao\Composer\ClientBackend->generate()
#9 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('composer')
#10 contao/main.php(20): Contao\BackendMain->run()
```

_Fehlerausgabe wurde optimiert um vollständige Meldungen zu haben._

**Comment by BugBuster1701** [comment]
Auch einige Aktualisierungen gehen nun nicht mehr!
[Forum](https://community.contao.org/de/showthread.php?63712-Aktualisierung-der-Paketverwaltung-nicht-m%F6glich&p=418026&viewfull=1#post418026)

**Comment by Brubbel66** [comment]
Ich habe ebenfalls Probleme, Legacy Pakete zu installieren.
Composer-Client wurde aus ER2 auf laufendes System installiert und hatte zunächst die Probleme mit dem https Zugriff, wie BugBuster1701 oben schreibt, für alle "übernommen" Legacy Pakete beim aktualisieren. Habe alle entfernt und nur 
Contao 3.5.15
composer-client 0.16.4
composer-plugin 2.4.3
drauf. Im Dateisystem alle Cacheunterordner geleert und die .lock und .phar Dateien entfernt und composer client aktualisiert.
Composer.json:
`{
    "name": "local/website",
    "description": "A local website project",
    "type": "project",
    "license": "proprietary",
    "require": {
        "contao-community-alliance/composer-client": ">=0.16.4.0,<0.17-dev"
    },
    "prefer-stable": true,
    "minimum-stability": "stable",
    "config": {
        "preferred-install": "dist",
        "cache-dir": "cache",
        "component-dir": "../assets/components"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://legacy-packages-via.contao-community-alliance.org/"
        },
        {
            "type": "artifact",
            "url": "packages"
        }
    ],
    "extra": {
        "contao": {
            "migrated": "done"
        }
    }
}`

Wenn ich das benötigte Paket **avisota/contao-bundle-all** suche, kann ich es installieren.
Wenn ich ein (beliebiges) Legacy Paket auswähle, z.B. **contao-legacy/backupdb**, dann erhalte ich immer diesen Fehler:

Fatal error: Uncaught exception Composer\Downloader\TransportException with message The "https://legacy-packages-via.contao-community-alliance.org/p/contao-legacy/backupdb%24f68c4946017aad3e1af511076b03e2b187259f73884b3e35b7b373b211894c02.json" file could not be downloaded (HTTP/1.1 404 Not Found) thrown in phar://composer/composer.phar/src/Composer/Util/RemoteFilesystem.php on line 368

#0 phar://composer/composer.phar/src/Composer/Util/RemoteFilesystem.php(101): Composer\Util\RemoteFilesystem->get('legacy-packages...', 'https://legacy-...', Array, NULL, false)
#1 phar://composer/composer.phar/src/Composer/Repository/ComposerRepository.php(646): Composer\Util\RemoteFilesystem->getContents('legacy-packages...', 'https://legacy-...', false)
#2 phar://composer/composer.phar/src/Composer/Repository/ComposerRepository.php(332): Composer\Repository\ComposerRepository->fetchFile('https://legacy-...', 'provider-contao...', 'f68c4946017aad3...', false)
#3 phar://composer/composer.phar/src/Composer/Repository/ComposerRepository.php(165): Composer\Repository\ComposerRepository->whatProvides(Object(Composer\DependencyResolver\Pool), 'contao-legacy/b...')
#4 phar://composer/composer.phar/src/Composer/Repository/CompositeRepository.php(91): Composer\Repository\ComposerRepository->findPackages('contao-legacy/b...', NULL)
#5 system/modules/!composer/src/Controller/SearchController.php(105): Composer\Repository\CompositeRepository->findPackages('contao-legacy/b...')
#6 system/modules/!composer/src/Controller/SearchController.php(53): ContaoCommunityAlliance\Contao\Composer\Controller\SearchController->searchPackages(Array, 1)
#7 system/modules/!composer/src/ClientBackend.php(213): ContaoCommunityAlliance\Contao\Composer\Controller\SearchController->handle(Object(Contao\Input))
#8 system/modules/core/classes/Backend.php(423): ContaoCommunityAlliance\Contao\Composer\ClientBackend->generate()
#9 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('composer')
#10 contao/main.php(20): Contao\BackendMain->run()
#11 {main}

**Comment by discordier** [comment]
I am monitoring the hits on the legacy server but have no clue why the files are being requested though.

Will have to perform further tests.

**Comment by discordier** [comment]
I am currently test driving an updated packagist server, expect results within the next days (if stability is as expected).

**Comment by BugBuster1701** [comment]
Interessant. "multicolumnwizard" stört nun nicht mehr. Aber bei suche nach "facebookconnect" kommt immer noch die Fehlermeldung.

**Comment by Brubbel66** [comment]
Bei mir kommt bei Suche nach "multicolumnwizard" weiterhin sofort der o.a. Fehler. 
Wenn ich auf der Webseite https://legacy-packages-via.contao-community-alliance.org schaue, steht beim Paket contao-legacy/multicolumnwizard dahinter, dass man für die aktuelle Version unter "menatwork/contao-multicolumnwizard" schauen soll. Wenn ich das im Paketmanager suche, kommt wie gewohnt die Übersichtsseite der Versionen und ich kann das Paket ohne Fehler der Paketliste hinzufügen. ABER: Wenn ich dann auf "Pakete aktualisieren" gehe, kommt nach einer Weile die Fehlermeldung:

The "https://legacy-packages-via.contao-community-alliance.org/p/contao-legacy/multicolumnwizard%241abe025852560b3f63471a7dc85c38ab34bfa09192b7a431c2dfcbbaa81803f4.json" file could not be downloaded (HTTP/1.1 404 Not Found)

Er sucht doch wieder an der alten Stelle?

**Comment by HStrandel** [comment]
Wenn ich auf Pakete aktualisieren klicke, erhalte ich folgende Fehlermeldung:

The "https://legacy-packages-via.contao-community-alliance.org/p/contao-legacy/tivoka%245e50bede571b88032f51d29accee7059dea701b975008ba9f51cbd76ca3b7f97.json" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by Brubbel66** [comment]
Aktuell sieht es (bei mir) wieder gut aus! Suche nach Paketen wirft keinen Fehler aus und "Pakete aktualisieren" läuft auch wieder sauber durch.  Toll!

**Comment by discordier** [comment]
Clearification, the new server is not live yet. I just wanted to inform you that I am aware of the problem and will put a replacement in service today.

**Comment by discordier** [comment]
The new server is live and updates to the latest package versions.

Operations should be back to normal now.

**Comment by Brubbel66** [comment]
A new error message apears:

The 'https://legacy-packages-via.contao-community-alliance.org/packages.json' URL could not be accessed: HTTP/1.1 403 Forbidden 

I searched for **avisota/contao-bundle-all**, got it, added it to the list and tried to update the package list. After a while, the message above appears.

**Comment by discordier** [comment]
Sorry, you seem to have hit the recreation of the package list, should not happen again.

**Comment by discordier** [comment]
No further notice, assuming fixed.
