### ISSUE TITLE
Why are dev-dependencies included?

### ISSUE THREAD

**Issue by Toflar** [contao-community-alliance/composer-client#295]
Can't we just ignore them? Why would you ever need them?

**Comment by discordier** [comment]
I do not understand what you mean... where are they included?
Are you talking about the list view in the backend?

**Comment by Toflar** [comment]
Every update says "including require dev" :-)

**Comment by Toflar** [comment]
Imho Composer should be executed using `--no-dev` which would be way faster.

**Comment by discordier** [comment]
Why should it be way faster if no dev dependencies are defined?
Have you run a benchmark?

Remember, dev dependencies are root only.
Granted, this section is empty for most users but it is by no means mandatory to be empty.

**Comment by Toflar** [comment]
> Remember, dev dependencies are root only.

Ah, true. Missed this. Was just confusing to see that message.
