### ISSUE TITLE
increase memory limit

### ISSUE THREAD

**Issue by fritzmg** [contao-community-alliance/composer-client#303]
Currently there is a function that tries to increase the `memory_limit` via `ini_set`: https://github.com/contao-community-alliance/composer-client/blob/0.16.5/src/system/modules/!composer/src/Runtime.php#L253-L289

However, it only tries to increase the memory limit to `1024M`. This might have been enough back when this function was first introduced, but the memory requirements have increased greatly since then, as we all know. (Noticed via http://stackoverflow.com/questions/41861627/php-out-of-memory-error-does-not-reflect-memory-limit-setting-in-php-ini)

So may be it makes sense to increase this. However it is known that even `2G` might not be enough - thus I don't think it should simply be set to a higher, hardcoded value.

May be it should simply be set to `-1` always? What do you think?

Also shouldn't `set_time_limit(0)` get added somewhere?

**Comment by discordier** [comment]
Changed in e4f4056. However, adding `set_time_limit(0)` seems to be way too risky as nowadays you will rather end up with a gateway timeout and leave the web server running the request until the end of times.

If really needed, the user should add it to `initconfig.php` by their own.
