### ISSUE TITLE
issue with legacy-packages

### ISSUE THREAD

**Issue by fritzmg** [contao-community-alliance/composer-client#306]
This is not an issue with the composer-client itself, but with the https://legacy-packages-via.contao-community-alliance.org package repository (not sure who to contact or where to post issues about that).

There appears to be an issue with some extensions from the ER2 at least. For instance see

* https://contao.org/en/extension-list/view/rocksolid-slider.en.html
* https://legacy-packages-via.contao-community-alliance.org/packages/contao-legacy/rocksolid-slider

None of the `1.6.x` versions from the ER2 are available via `contao-legacy`.

https://community.contao.org/de/showthread.php?65586-Erweiterungen-laufen-nicht-mit-Composer

**Comment by discordier** [comment]
Will check, thanks for notifying.

**Comment by discordier** [comment]
Problem is fixed. We simply did not check for updates on any "abandoned" package anymore.

While this is a good idea on regular composer packages it makes no sense in our legacy gateway and therefore I have reverted this functionality.

All should be up and running again, the latest updates are still being absorbed at time of writing this.
