### ISSUE TITLE
Zurück-Link bei Suchergebnissen verwirrend

### ISSUE THREAD

**Issue by LukasMusilek** [contao-community-alliance/composer-client#310]
Ist es gewollt, dass der "Zurück"-Link bei der Detailansicht eines zu installierenden Paketes nicht zur Liste mit den vorherigen Suchergebnissen sondern zur Liste der installierten Pakete führt? 

Ich finde es nervig und zeitaufwendig, bei der Suche nach einem bestimmten Paket immer wieder den Suchbegriff neu eingeben zu müssen, nachdem ich die Detailseite eines Paketes angesehen habe. 
Einen Backlink zur Liste der Suchergebnisse fände ich viel intuitiver und praktischer.

**Comment by backbone87** [comment]
escaping fehler im commit, siehe comments im commit

**Comment by discordier** [comment]
Thanks, will fix.
