### ISSUE TITLE
Client tries to resolve unnecessary dependencies while updating packages.

### ISSUE THREAD

**Issue by beaniemonk** [contao-community-alliance/composer-client#311]
**My configuration:**
- Contao v3.5.24
- Composer-Client v0.16.5
- Composer runs in standalone mode
- Composer is updated, cache is cleared, and packages are resynced

**My Issue:**
When I install or update packages, most work normally. But there are a few that cause Composer to download an excessive number of unnecessary dependencies, including a bunch of Symfony packages that aren't needed or used anywhere. I had to increase the swap of my development server because Composer was running out of memory and failing.

One example is `codefog/contao-widget_tree_picker`. But I've come across a few others as well (e.g. `terminal42/contao-ce-access`).

I asked Codefog about it, and he suggested I post it here, thinking it might be an issue with Composer-Client module itself.

I attached the composer.json file below that I can reproduce the issue with:

**My composer.json file:**
[composer.json.txt](https://github.com/contao-community-alliance/composer-client/files/828389/composer.json.txt)

**The complete debug output when updating packages:**
[composer-output.txt](https://github.com/contao-community-alliance/composer-client/files/828392/composer-output.txt)

**A screenshot of my /composer/ folder, and how the Package Manager looks in the backend:**
[screenshot.jpg](https://cloud.githubusercontent.com/assets/1709265/23715101/87836e0a-03f9-11e7-9a57-13befad0cef7.jpg)

**Comment by fritzmg** [comment]
> A screenshot of my /composer/ folder, and how the Package Manager looks in the backend:
> screenshot.jpg

Looks normal. There are no packages listed, that aren't needed. If you are refering to the Contao Bundles, those are injected by the `composer-plugin` and not really downloaded, as you can see yourself.

**Comment by beaniemonk** [comment]
> How did you come to this conclusion?

By looking at the output generated when updating packages (it's attached to my original message).

The screenshot isn't meant to show you the issue. The screenshot is meant to show you that I don't have any packages installed that explain what I see when I do an update.


Let me put it another way. Let's do a few quick tests...

**1. Let's remove all the packages from Composer (leaving only the Composer Client):**

The composer.json file [looks like this](https://github.com/contao-community-alliance/composer-client/files/829460/empty.composer.json.txt). When I update packages, the output [looks like this](https://github.com/contao-community-alliance/composer-client/files/829463/empty-output.txt). Everything looks normal so far. It analyzed 712 packages and 7,325 rules.


**2. Let's add one package that I think works as it should:**

I'll even stick with the same author and install `codefog/contao-custom_module`. Now the composer.json file [looks like this](https://github.com/contao-community-alliance/composer-client/files/829461/good.composer.json.txt), and when I update packages, the output [looks like this](https://github.com/contao-community-alliance/composer-client/files/829458/good-output.txt).  Everything still looks normal. It analyzed 717 packages and 7,333 rules.


**3. Now let's remove that package and replace it with one that I think isn't working right:**

I'll remove `codefog/contao-custom_module` and replace it with `codefog/contao-widget_tree_picker`. Now composer.json [looks like this](https://github.com/contao-community-alliance/composer-client/files/829459/bad.composer.json.txt), and the output [looks like this](https://github.com/contao-community-alliance/composer-client/files/829462/bad-output.txt). 

As you can see, suddenly the number of packages analyzed balloons to 6,910 and the number of rules analyzed balloons to 386,766. If you take a closer look, you'll see that composer tried to resolve, among other things, a whole bunch of Symfony packages that are not related to anything.

And this is pretty simple module. It's maybe 15 files and no additional dependencies. But trying to install this one package caused Composer to eat up over 1GB of RAM, run out of memory, and fail. And it isn't just this one. I've come across 4 or 5 spanning multiple authors.

Hence, the conclusion that I came to. :)

**Comment by discordier** [comment]
What makes you think that the symfony packages do not relate to anything?

Let me show you one example (among many) that proves that symfony packages are related:
1. `codefog/contao-widget_tree_picker: 2.3.2` requires `contao/core-bundle: ~3.5 || ~4.1`
2. `contao/core-bundle: 4.3.5` requires a whole lot of symfony packages

The fact that you are running Contao 3.5 is not known in this phase and therefore all related package combinations have to get retrieved and examined.

This is however an issue of composer itself and not an issue of our GUI wrapped around composer.

**Comment by beaniemonk** [comment]
I understand, thank you. That explains the differences between packages.

> What makes you think that the symfony packages do not relate to anything?

What you've just explained makes perfect sense to me and clears everything up. 

However, I do not believe that you genuinely do not understand how I could think that. You're just trying to be cheeky, right?

Regardless thanks again.

**Comment by discordier** [comment]
It was rather rhetoric :smile:

**Comment by beaniemonk** [comment]
```
{
    "name": "beaniemonk/dry-sarcasm",
    "description": "The nerdiest joke I've ever told.",
    "require": { 
        "symfony$expression-rhetoric": "~3.7",
        "discordier/rhetoric-server": ">=2.4,<3.0" 
    }
}
```
