### ISSUE TITLE
PHP 7.1 Anpassung

### ISSUE THREAD

**Issue by BugBuster1701** [contao-community-alliance/composer-client#312]
Ich habe über install.php auf composer umstellen lassen.
Im Backend wurde dann der Client installiert aber abgebrochen mit folgender Meldung:
```
Fatal error: Uncaught exception Error with message [] operator not supported for strings thrown in system/modules/!composer/src/Client.php on line 79

#0 system/modules/core/library/Contao/System.php(340): ContaoCommunityAlliance\Contao\Composer\Client->disableOldClientHook('default', 'de', 'de')
#1 system/modules/core/controllers/BackendMain.php(96): Contao\System::loadLanguageFile('default')
#2 contao/main.php(19): Contao\BackendMain->__construct()
#3 {main}
```
In Zeile 79 ist `$inactiveModules` offenbar ein String (gesetzt in Zeile 76)  laut Fehlermeldung, die Variable wird in Zeile 79 versucht über `[]` in diesem Fall in ein Array zu wandeln, genau das ist in PHP 7.0 noch möglich, in 7.1 nicht mehr.

Siehe [php.net incompatible.empty-string-index-operator](https://secure.php.net/manual/en/migration71.incompatible.php#migration71.incompatible.empty-string-index-operator)

Habe mir beholfen in Zeile 76 ein Array zu erzwingen:

`$inactiveModules = (array) deserialize($GLOBALS['TL_CONFIG']['inactiveModules']);`

**Comment by fritzmg** [comment]
Duplicate of #305

**Comment by BugBuster1701** [comment]
OK.
