### ISSUE TITLE
Contao 3.5.36 can't install composer

### ISSUE THREAD

**Issue by xApep** [contao-community-alliance/composer-client#317]
Hi. I'm using Windows and WAMP. Is there any requirement to install composer (I have installed composer via windows setup)?

When I click Install composer, nothing happens.

![image](https://user-images.githubusercontent.com/1315340/46421531-91033980-c732-11e8-9896-54fd2260783a.png)

Thanks.

**Comment by baumannsven** [comment]
I don't know anything about wamp and composer. Please check if composer.phar is available in the composer directory. If not then get it from getcomposer.org and put it there and try again.

**Comment by xApep** [comment]
Thanks for the solution ;)

But damn, we had to set max memory to unlimited to Update package :D

**Comment by baumannsven** [comment]
This must you set on your php.ini. Search for it.

**Comment by xApep** [comment]
Yeah, I'm just saying that we had to increase memory to unlimited so that there was no fatal error "out of memory". 

Thanks for help @baumannsven ;)
