### ISSUE TITLE
SSL-Zertifikat contao-community-alliance.org

### ISSUE THREAD

**Issue by SGehle** [contao-community-alliance/composer-client#318]
Das SSL-Zertifikat der Domain contao-community-alliance.org scheint ausgelaufen zu sein...

The "https://legacy-packages-via.contao-community-alliance.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed Failed to enable crypto failed to open stream: operation failed

**Comment by frontendschlampe** [comment]
jo ... sorry ... wir schauen dann mal, warum es nicht automatisch aktualisiert wurde! Hat die letzten Monate eigentlich immer funktioniert!

**Comment by SGehle** [comment]
@frontendschlampe  Danke!

**Comment by discordier** [comment]
Sollte wieder gehen, `c-c-a.org` und `contao-community-alliance.org` sind wieder sauber integriert.
