### ISSUE TITLE
[notice] Proxy support

### ISSUE THREAD

**Issue by tristanlins** [contao-community-alliance/composer-client#74]
We should have a look at composer/composer#1991 for proxy support.

**Comment by cristian-lorenzetto-pa** [comment]
sudo composer diagnose
[sudo] password di d77154: 
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "http://packagist.org/packages.json" file could not be downloaded (HTTP/1.1 404 Not Found)
Checking https connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: Peer certificate CN=`*.comune.fi.it' did not match expected CN=`packagist.org'
Failed to enable crypto
failed to open stream: operation failed
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: Peer certificate CN=`*.comune.fi.it' did not match expected CN=`api.github.com'
Failed to enable crypto
failed to open stream: operation failed
Checking disk free space: OK
Composer version: 1.6.3
PHP version: 7.2.24-0ubuntu0.18.04.1
PHP binary path: /usr/bin/php7.2
